import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dinroundpro = localFont({
  src: [
    {
      path: "./fonts/dinroundpro_black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_medi.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dinroundpro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${dinroundpro.variable} bg-background text-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
