import { UserProvider } from "@/context/UserContext";
import { Navbar } from "@/ui/components/navbar/Navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dinroundpro = localFont({
  src: [
    {
      path: "./fonts/dinroundpro_black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro_medi.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/dinroundpro.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dinroundpro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "H2Ocean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${dinroundpro.variable} bg-background text-white antialiased`}
      >
        <UserProvider>
          <div className="flex max-md:flex-col min-h-screen max-h-screen">
            <Navbar className="w-[300px]" />
            <div className="h-full ml-[300px] max-md:ml-0 w-full max-md:w-auto px-[40px] py-[40px] max-md:p-[20px] max-md:py-[20px] max-sm:p-[20px]">
              {children}
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
